import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  ArrowRight,
  BarChart3,
  BookOpen,
  Car,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Gauge,
  Home,
  Info,
  KeyRound,
  Languages,
  ListChecks,
  Lightbulb,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPinned,
  ParkingCircle,
  PartyPopper,
  RotateCcw,
  Search,
  Settings,
  ShieldCheck,
  Signal,
  Target,
  Timer,
  TrafficCone,
  TrendingUp,
  Trophy,
  User,
  XCircle
} from "lucide-react";

export const Icons = {
  book: BookOpen,
  car: Car,
  map: Map,
  mapPinned: MapPinned,
  speed: Gauge,
  parking: ParkingCircle,
  safety: ShieldCheck,
  signs: TrafficCone,
  languages: Languages,
  progress: BarChart3,
  mock: ClipboardCheck,
  timer: Timer,
  checklist: ListChecks,
  fileText: FileText,
  info: Info,
  user: User,
  settings: Settings,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  lock: Lock,
  key: KeyRound,
  eye: Eye,
  eyeOff: EyeOff,
  warning: AlertTriangle,
  success: CheckCircle2,
  error: XCircle,
  reset: RotateCcw,
  trophy: Trophy,
  target: Target,
  home: Home,
  search: Search,
  external: ExternalLink,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  /** Traffic lights topic (no `TrafficLight` export in this lucide-react version). */
  trafficSignal: Signal,
  loader: Loader2,
  party: PartyPopper,
  lightbulb: Lightbulb,
  trendingUp: TrendingUp
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
